# Category 3: Mindset (Target: 182)
# Category 4: Life (Target: 182)

MINDSET = [
    # 1-word
    "Resilience", "Stoicism", "Mindfulness", "Discipline", "Optimism",
    "Pessimism", "Perfectionism", "Introspection", "Vulnerability", "Humility",
    "Patience", "Gratitude", "Ambition", "Curiosity", "Adaptability",
    "Perseverance", "Confidence", "Courage", "Tenacity", "Decisiveness",
    "Proactivity", "Detachment", "Empathy", "Equanimity", "Assertiveness",
    "Sincerity", "Altruism", "Intention", "Determination", "Compassion",
    "Reflection", "Fortitude", "Boldness", "Pragmatism", "Self-Awareness",
    "Self-Control", "Self-Reliance", "Self-Efficacy", "Self-Compassion", "Self-Regulation",
    # 2-word
    "Growth Mindset", "Fixed Mindset", "Imposter Syndrome", "Emotional Intelligence", "Mental Toughness",
    "Deep Focus", "Cognitive Bias", "Delayed Gratification", "Habit Formation", "Overcoming Failure",
    "Inner Peace", "Positive Psychology", "Critical Thinking", "Creative Confidence", "Lateral Thinking",
    "Morning Routines", "Evening Routines", "Stress Management", "Burnout Prevention", "Mental Models",
    "First Principles", "Inversion Thinking", "Second-Order Thinking", "Systems Thinking", "Cognitive Flexibility",
    "Decision Fatigue", "Willpower Depletion", "Flow State", "Peak Performance", "Active Listening",
    "Self Discipline", "Emotional Agility", "Radical Acceptance", "Inner Critic", "Negative Self-Talk",
    "Cognitive Reframing", "Neuroplasticity Habits", "Growth Oriented", "Daily Journaling", "Mindful Breathing",
    "Meditation Practice", "Silent Retreats", "Solitude Seeking", "Information Diet", "Mental Clarity",
    "Brain Fog", "Attentional Control", "Focused Attention", "Diffuse Mode", "Habit Loops",
    "Cue Response", "Dopamine Detox", "Self Accountability", "Personal Responsibility", "Internal Locus",
    "External Locus", "Learned Helplessness", "Learned Optimism", "Unconscious Bias", "Confirmation Bias",
    "Sunk Cost", "Availability Heuristic", "Anchoring Bias", "Dunning-Kruger Effect", "Overconfidence Bias",
    "Status Quo", "Loss Aversion", "Risk Tolerance", "Calculated Risks", "Fear Setting",
    "Worst-Case Scenarios", "Proactive Thinking", "Reactive Thinking", "Solution Oriented", "Problem Solving",
    "Adaptive Thinking", "Mindset Shift", "Identity Shift", "Core Beliefs", "Limiting Beliefs",
    "Cognitive Dissonance", "Moral Courage", "Intellectual Humility", "Open Mindedness", "Perspective Taking",
    "Empathic Accuracy", "Compassion Fatigue", "Emotional Balance", "Inner Strength", "Psychological Safety",
    "Fear Failure", "Fear Success", "Perfectionist Trap", "Good Enough", "Progress Focus",
    "Outcome Independence", "Process Focus", "Continuous Improvement", "Kaizen Philosophy", "Atomic Habits",
    "Micro Habits", "Keystone Habits", "Habit Stacking", "Willpower Reserve", "Daily Intentions",
    "Purpose Driven", "Value Alignment", "Moral Compass", "Inner Compass", "Self Actualization",
    "Self Acceptance", "Radical Honesty", "Vulnerability Strength", "Healthy Boundaries", "Saying No",
    "People Pleasing", "Setting Limits", "Mental Resilience", "Bouncing Back", "Adversity Quotient",
    "Emotional Maturity", "Patience Practice", "Grace Under", "Self Mastery", "Mind Mastery",
    "Emotional Awareness", "Conscious Living", "Present Moment", "Being Present", "Mindful Living",
    "Mind Wandering", "Daydreaming Benefits", "Quiet Ego", "Ego Transcendence", "Self Transcendence",
    "Inner Calm", "Mental Stamina", "Constructive Criticism", "Receiving Feedback", "Giving Feedback",
    "Self Correction", "Behavioral Change", "Positive Reinforcement", "Negative Reinforcement", "Intrinsic Motivation",
    "Extrinsic Motivation", "Goal Setting", "Vision Boards", "Daily Affirmations", "Mental Rehearsal",
    "Visualization Techniques", "Grounding Techniques", "Somatic Awareness", "Body Language", "Subconscious Mind",
    "Intuitive Thinking", "Rational Thinking", "Analytical Thinking", "Holistic Thinking", "Convergent Thinking",
    "Divergent Thinking", "Creative Visualization", "Unlearning Habits", "Challenging Assumptions", "Embracing Uncertainty"
]

LIFE = [
    # 1-word
    "Longevity", "Happiness", "Solitude", "Friendship", "Relationships",
    "Wellness", "Belonging", "Marriage", "Parenting", "Nutrition",
    "Simplicity", "Fitness", "Sleep", "Leisure", "Grief",
    "Forgiveness", "Nostalgia", "Playfulness", "Community", "Mortality",
    "Aging", "Independence", "Wholesomeness", "Balance", "Companionship",
    "Stillness", "Adventure", "Generosity", "Hospitality", "Neighborliness",
    "Contentment", "Kinship", "Vitality", "Recovery", "Brotherhood",
    "Sisterhood", "Heritage", "Savoring", "Frugality", "Quiet Moments",
    # 2-word
    "Work-Life Balance", "Healthy Eating", "Intermittent Fasting", "Physical Fitness", "Mental Health",
    "Sleep Hygiene", "Circadian Rhythms", "Preventive Health", "Chronic Illness", "Holistic Health",
    "Healthy Aging", "Active Aging", "Family Dynamics", "Blended Families", "Sibling Rivalry",
    "Empty Nest", "Child Rearing", "Modern Parenting", "Screen-Free Parenting", "Quality Time",
    "Meaningful Conversations", "Long-Distance Friendship", "Deep Friendships", "Social Circles", "Community Living",
    "Co-Living Spaces", "Intentional Communities", "Neighborhood Watch", "Village Life", "Rural Living",
    "City Living", "Slow Living", "Simple Living", "Tiny Homes", "Minimalist Lifestyle",
    "Conscious Consumption", "Material Attachment", "Letting Go", "Decluttering Spaces", "Capsule Wardrobe",
    "Financial Wellness", "Emergency Fund", "Debt-Free Living", "Saving Habits", "Conscious Spending",
    "Personal Budget", "Retirement Planning", "Work Retirement", "Second Acts", "Midlife Transition",
    "Quarter-Life Crisis", "Rite Passage", "Modern Rituals", "Sacred Spaces", "Home Sanctuary",
    "Plant Care", "Urban Gardening", "Pet Ownership", "Animal Companionship", "Outdoor Recreation",
    "Forest Bathing", "Nature Therapy", "Sun Exposure", "Clean Living", "Hydration Habits",
    "Daily Movement", "Sedentary Lifestyle", "Posture Health", "Eye Strain", "Screen Fatigue",
    "Digital Balance", "Unplugged Weekends", "Campfire Talks", "Road Trips", "Travel Experiences",
    "Solo Travel", "Cultural Immersion", "Language Learning", "Lifelong Hobbies", "Board Games",
    "Reading Habits", "Culinary Arts", "Home Cooking", "Shared Meals", "Sunday Dinner",
    "Family Traditions", "Holiday Rituals", "Memory Making", "Photo Albums", "Oral History",
    "Ancestral Roots", "Family Trees", "Generational Healing", "Caregiver Burden", "Eldercare Solutions",
    "Nursing Homes", "Hospice Care", "End-Of-Life Care", "Living Wills", "Grieving Process",
    "Bereavement Support", "Healing Trauma", "Emotional Recovery", "Personal Transformation", "Finding Purpose",
    "Meaning Search", "Existential Dread", "Midlife Reflections", "Wisdom Gathering", "Age Gracefully",
    "Celebrating Milestones", "Personal Milestones", "Bucket Lists", "Unplanned Adventures", "Simple Pleasures",
    "Daily Gratitude", "Evening Walks", "Stargazing Nights", "Morning Coffee", "Tea Rituals",
    "Slow Mornings", "Restful Sundays", "Digital Sabbath", "Social Connections", "Overcoming Loneliness",
    "Chronic Loneliness", "Finding Community", "Making Friends", "Adult Friendships", "Mutual Support",
    "Safe Spaces", "Listening Closely", "Unconditional Love", "Romantic Love", "Companionate Love",
    "Long-Term Relationships", "Relationship Maintenance", "Communication Styles", "Conflict Resolution", "Constructive Arguments",
    "Forgiving Others", "Forgiving Yourself", "Second Chances", "Rebuilding Trust", "Unspoken Expectations",
    "Mutual Respect", "Emotional Intimacy", "Physical Touch", "Quality Presence", "Shared Vulnerability",
    "Active Play", "Childhood Games", "Weekend Getaways", "Backyard Camping", "Spontaneous Gatherings",
    "Cooking Together", "Baking Bread", "Morning Walks", "Sunset Watching", "Restful Sleep"
]
