# Category 7: Future (Target: 182)
# Category 8: Environment (Target: 182)

FUTURE = [
    # 1-word
    "Transhumanism", "Colonization", "Terraforming", "Cyborgs", "Teleportation",
    "Singularity", "Cryonics", "Megastructures", "Superintelligence", "Androids",
    "Nanomedicine", "Astroengineering", "Hyperloop", "Spacefaring", "Posthumanism",
    "Futurism", "Exoplanets", "Biospheres", "Astrobiology", "Antimatter",
    "Extinction", "Telepathy", "Interstellar", "Utopia", "Dystopia",
    "Extraterrestrials", "Bioprinting", "Superlongevity", "Rejuvenation", "Post-Scarcity",
    "Megacities", "Biomimicry", "Transhuman", "Neurotech", "Cyberware",
    "Post-Human", "Cryopreservation", "Nanofactories", "Spaceplanes", "Alien Biospheres",
    # 2-word
    "Space Exploration", "Deep Space", "Lunar Base", "Mars Colonization", "Asteroid Mining",
    "Space Tourism", "Orbital Habitats", "Space Elevators", "Interplanetary Travel", "Fusion Energy",
    "Clean Energy", "Autonomous Transportation", "Flying Vehicles", "Urban Air", "Hyperloop Transit",
    "High-Speed Rail", "Supersonic Flight", "Brain Uploading", "Mind Transfer", "Artificial General",
    "Artificial Superintelligence", "Technological Singularity", "Post-Human Era", "Synthetic Life", "Genetic Enhancement",
    "Designer Babies", "Cellular Agriculture", "Lab-Grown Meat", "Vertical Farming", "Deep Sea",
    "Ocean Habitats", "Floating Cities", "Underground Cities", "Arcology Design", "Planetary Defense",
    "Asteroid Deflection", "Space Debris", "Orbital Debris", "Mega Constellations", "Space Telescopes",
    "Quantum Internet", "Holographic Displays", "Augmented Senses", "Neural Lace", "Brain Implants",
    "Consciousness Uploading", "Digital Afterlife", "Immortality Research", "Age Reversal", "Regenerative Medicine",
    "Organ Printing", "Synthetic Organs", "Bionic Limbs", "Exoskeleton Suits", "Cybernetic Enhancements",
    "Memory Editing", "Cognitive Augmentation", "Genetic Editing", "Gene Drives", "De-Extinction Projects",
    "Synthetic Ecosystems", "Climate Engineering", "Geoengineering Solutions", "Solar Radiation", "Carbon Sequestration",
    "Direct Air", "Atmospheric Scrubbing", "Post-Labor Society", "Automated Economy", "Post-Scarcity Economics",
    "Universal Abundance", "Automated Governance", "Algorithmic Law", "Digital Democracy", "Planetary Governance",
    "Global Federation", "Post-Nation States", "Sovereign Individuals", "Virtual Worlds", "Immersive Realities",
    "Neural Metaverse", "Digital Consciousness", "Synthetic Humans", "Android Rights", "Robot Consciousness",
    "Machine Rights", "Post-Biological Intelligence", "Extraterrestrial Intelligence", "SETI Research", "Fermi Paradox",
    "Great Filter", "Kardashev Scale", "Dyson Spheres", "Stellar Engines", "Wormhole Physics",
    "Relativistic Travel", "Generation Ships", "Sleeper Ships", "Human Hibernation", "Space Medicine",
    "Microgravity Health", "Artificial Gravity", "Planetary Terraform", "Atmosphere Generation", "Magnetic Shields",
    "Cosmic Radiation", "Interstellar Probes", "Self-Replicating Probes", "Galactic Mapping", "Space Law",
    "Outer Space", "Planetary Protection", "Deep Future", "Cosmic Horizon", "Dark Energy",
    "Quantum Foam", "Time Dilatation", "Multiverse Hypothesis", "Parallel Universes", "Simulated Reality",
    "Quantum Superposition", "Planetary Stewardship", "Solar Sails", "Ion Propulsion", "Nuclear Thermal",
    "Plasma Engines", "Gravitational Waves", "Tachyon Particles", "Zero-Point Energy", "Space Architecture",
    "Lunar Geology", "Martian Soil", "In-Situ Resource", "Closed-Loop Systems", "Life Support",
    "Orbital Manufacturing", "Zero-Gravity Research", "Space Refueling", "Space Missions", "Interstellar Travel",
    "Warp Fields", "Faster-Than-Light", "Stargate Technology", "Telescope Arrays", "Exoplanet Atmospheres",
    "Habitable Zones", "Goldilocks Planets", "Tidally Locked", "Ocean Worlds", "Subsurface Oceans"
]

ENVIRONMENT = [
    # 1-word
    "Conservation", "Sustainability", "Biodiversity", "Ecology", "Deforestation",
    "Reforestation", "Renewable", "Ecosystems", "Rewilding", "Permaculture",
    "Pollution", "Composting", "Oceanography", "Climate", "Decarbonization",
    "Biosphere", "Wilderness", "Wetlands", "Rainforests", "Glaciers",
    "Desalination", "Overfishing", "Microplastics", "Acidification", "Drought",
    "Aquifers", "Watersheds", "Wildfires", "Eco-Tourism", "Upcycling",
    "Recycling", "Landfills", "Defaunation", "Biogeography", "Agroecology",
    "Ecosystem", "Eco-Restoration", "Reforest", "Afforestation", "Degradation",
    # 2-word
    "Climate Change", "Global Warming", "Greenhouse Gases", "Carbon Footprint", "Net Zero",
    "Renewable Energy", "Solar Power", "Wind Energy", "Geothermal Energy", "Hydroelectric Power",
    "Tidal Energy", "Wave Energy", "Nuclear Fusion", "Nuclear Fission", "Clean Tech",
    "Carbon Offsetting", "Carbon Taxes", "Emission Standards", "Fossil Fuels", "Coal Phaseout",
    "Oil Depletion", "Energy Transition", "Electric Vehicles", "Battery Recycling", "Grid Storage",
    "Green Hydrogen", "Biofuel Production", "Circular Economy", "Zero Waste", "Plastic Pollution",
    "Ocean Cleanup", "Coral Bleaching", "Marine Protected", "Sustainable Fishing", "Overfishing Solutions",
    "Mangrove Restoration", "Coastal Protection", "Sea Level", "Rising Oceans", "Melting Glaciers",
    "Arctic Ice", "Permafrost Thaw", "Extreme Weather", "Heat Waves", "Drought Resilience",
    "Desertification Control", "Soil Degradation", "Soil Health", "Regenerative Agriculture", "Cover Crops",
    "No-Till Farming", "Organic Farming", "Agroforestry Practices", "Vertical Agriculture", "Precision Agriculture",
    "Water Conservation", "Drip Irrigation", "Rainwater Harvesting", "Aquifer Depletion", "Freshwater Scarcity",
    "Desalination Plants", "Wastewater Treatment", "River Restoration", "Wetland Preservation", "Forest Management",
    "Wildfire Prevention", "Controlled Burns", "Endangered Species", "Wildlife Corridors", "Habitat Fragmentation",
    "Biodiversity Loss", "Species Extinction", "Invasive Species", "Poaching Prevention", "Wildlife Sanctuaries",
    "National Parks", "Wilderness Protection", "Ecotourism Standards", "Sustainable Forestry", "Timber Certification",
    "Green Architecture", "Passive Solar", "Energy Efficiency", "LEED Certification", "Sustainable Materials",
    "Hemp Building", "Mass Timber", "Green Roofs", "Urban Canopy", "Heat Island",
    "Light Pollution", "Noise Pollution", "Air Quality", "Smog Control", "Industrial Emissions",
    "Toxic Waste", "Chemical Pollution", "Pesticide Runoff", "Eutrophication Events", "Ocean Acidification",
    "Plastic Bans", "Single-Use Plastics", "Biodegradable Packaging", "Composting Programs", "Food Waste",
    "Circular Food", "Plant-Based Diets", "Sustainable Sourcing", "Environmental Justice", "Climate Refugees",
    "Climate Adaptation", "Resilience Planning", "Disaster Preparedness", "Flood Defenses", "Sea Walls",
    "Nature-Based Solutions", "Forest Carbon", "Soil Carbon", "Peatland Restoration", "Blue Carbon",
    "Ocean Alkalinity", "Cloud Brightening", "Ecological Balance", "Riparian Buffers", "Watershed Protection",
    "Stream Restoration", "Estuary Health", "Coral Propagation", "Artificial Reefs", "Seagrass Meadows",
    "Kelp Forests", "Algal Blooms", "Toxics Reduction", "Hazardous Waste", "Superfund Sites",
    "Lead Contamination", "PFAS Contamination", "Forever Chemicals", "Groundwater Remediation", "Mine Reclamation",
    "Brownfield Redevelopment", "Urban Ecology", "Ecological Footprint", "Overshoot Day", "Planetary Boundaries",
    "Carrying Capacity", "Resource Depletion", "Mineral Extraction", "Rare Earths", "Green Mining"
]
