# Category 9: Science (Target: 182)
# Category 10: People (Target: 181)
# Category 11: Creativity (Target: 181)

SCIENCE = [
    # 1-word
    "Genetics", "Astrophysics", "Neuroscience", "Chemistry", "Biology",
    "Physics", "Geology", "Paleontology", "Meteorology", "Immunology",
    "Thermodynamics", "Virology", "Pharmacology", "Seismology", "Astronomy",
    "Biochemistry", "Crystallography", "Volcanology", "Entomology", "Botany",
    "Zoology", "Epigenetics", "Biomechanics", "Electromagnetism", "Optics",
    "Cosmology", "Anthropology", "Archaeology", "Taxonomy", "Climatology",
    "Bioinformatics", "Toxicology", "Geophysics", "Oceanology", "Parasitology",
    "Mineralogy", "Embryology", "Neurobiology", "Microbiology", "Speciation",
    # 2-word
    "Quantum Mechanics", "General Relativity", "Special Relativity", "Black Holes", "Dark Matter",
    "String Theory", "Particle Physics", "Higgs Boson", "Standard Model", "Nuclear Physics",
    "Atomic Structure", "Periodic Table", "Chemical Bonding", "Organic Chemistry", "Molecular Biology",
    "Genetic Code", "DNA Sequencing", "CRISPR Technology", "Gene Therapy", "Epigenetic Modifications",
    "Cellular Respiration", "Stem Cells", "Regenerative Biology", "Evolutionary Biology", "Natural Selection",
    "Speciation Events", "Fossil Record", "Continental Drift", "Plate Tectonics", "Earth Mantle",
    "Deep Core", "Volcanic Activity", "Seismic Waves", "Magnetic Field", "Solar Flares",
    "Cosmic Rays", "Supernova Explosions", "Neutron Stars", "Pulsar Signals", "Quasar Emission",
    "Galaxy Clusters", "Cosmic Background", "Big Bang", "Space-Time Fabric", "Event Horizon",
    "Singularity Physics", "Quantum Entanglement", "Quantum Tunneling", "Wave-Particle Duality", "Uncertainty Principle",
    "Quantum Coherence", "Superconductivity Principles", "Superfluid Dynamics", "Plasma Physics", "Fusion Reactions",
    "Fission Mechanics", "Radioactive Decay", "Half-Life Dynamics", "Carbon Dating", "Particle Accelerators",
    "Synchrotron Light", "Electron Microscopy", "Atomic Force", "Spectroscopy Methods", "Chromatography Techniques",
    "Mass Spectrometry", "X-Ray Diffraction", "Nanoscale Engineering", "Molecular Motors", "Cellular Signaling",
    "Synaptic Plasticity", "Neurotransmitters Pathways", "Brain Hemispheres", "Cognitive Neuroscience", "Memory Consolidation",
    "Sensory Perception", "Auditory Processing", "Visual Cortex", "Motor Control", "Circadian Clock",
    "Immune Response", "Antibody Structure", "T-Cell Immunity", "Vaccine Science", "Herd Immunity",
    "Pathogen Evolution", "Antibiotic Resistance", "Viral Replication", "Zoonotic Diseases", "Epidemiology Models",
    "Clinical Trials", "Placebo Effect", "Double-Blind Studies", "Scientific Method", "Hypothesis Testing",
    "Statistical Significance", "P-Value Debate", "Replicability Crisis", "Open Science", "Citizen Science",
    "Scientific Ethics", "Animal Testing", "Bioethics Standards", "Space Astronomy", "Radio Telescopes",
    "Optical Telescopes", "Infrared Astronomy", "Gravitational Lensing", "Cosmic Inflation", "Origin Life",
    "Prebiotic Chemistry", "RNA World", "Abiogenesis Theories", "Extremophile Organisms", "Hydrothermal Vents",
    "Subglacial Lakes", "Astrobiology Research", "Planetary Science", "Martian Atmosphere", "Cometary Composition",
    "Meteorite Impacts", "Planetary Nebulae", "Stellar Evolution", "White Dwarfs", "Magnetar Fields",
    "Gamma-Ray Bursts", "Cosmic Web", "Gravitational Collapse", "Stellar Nucleosynthesis", "Heavy Elements",
    "Superheavy Atoms", "Quantum Electrodynamics", "Quantum Chromodynamics", "Quark-Gluon Plasma", "Boson Condensate",
    "Entropy Laws", "Heat Death", "Thermal Equilibrium", "Statistical Mechanics", "Chaos Theory",
    "Complex Systems", "Nonlinear Dynamics", "Fractal Geometry", "Fluid Dynamics", "Aerodynamic Principles",
    "Turbulent Flow", "Laminar Flow", "Kinetic Energy", "Potential Energy", "Electromagnetic Radiation",
    "Radio Waves", "Microwave Background", "Infrared Spectrum", "Visible Light", "Ultraviolet Radiation"
]

PEOPLE = [
    # 1-word
    "Altruists", "Philosophers", "Visionaries", "Explorers", "Inventors",
    "Innovators", "Polymaths", "Statesmen", "Diplomats", "Reformers",
    "Whistleblowers", "Pioneers", "Storytellers", "Orators", "Humanitarians",
    "Polyglots", "Philanthropists", "Heroes", "Freethinkers", "Trailblazers",
    "Thinkers", "Strategists", "Champions", "Advocates", "Builders",
    "Pathfinders", "Peacemakers", "Artisans", "Mentors", "Proteges",
    "Iconoclasts", "Revolutionaries", "Visionary", "Statesman", "Diplomat",
    "Activist", "Trailblazer", "Explorer", "Pioneer", "Inventor",
    # 2-word
    "Historical Figures", "World Leaders", "Nobel Laureates", "Scientific Pioneers", "Social Reformers",
    "Civil Activists", "Moral Exemplars", "Unsung Heroes", "Everyday Heroes", "Visionary Thinkers",
    "Inspiring Teachers", "Thought Leaders", "Community Champions", "Youth Activists", "Cultural Icons",
    "Master Craftsmen", "Lifelong Mentors", "Inspiring Figures", "Human Nature", "Empathy Action",
    "Compassionate Leaders", "Servant Leaders", "Ethical Pioneers", "Courageous Voices", "Independent Thinkers",
    "Creative Geniuses", "Legendary Authors", "Visionary Artists", "Pioneering Doctors", "Humanitarian Workers",
    "First Responders", "Healthcare Workers", "Brave Soldiers", "Peacemaking Diplomats", "Influential Voices",
    "Global Citizens", "Grassroots Organizers", "Labor Leaders", "Rights Champions", "Environmental Champions",
    "Women Pioneers", "Youth Leaders", "Elder Wisdom", "Indigenous Elders", "Cultural Ambassadors",
    "Public Servants", "Dedicated Educators", "Groundbreaking Scientists", "Brave Explorers", "Polar Explorers",
    "Mountaineering Pioneers", "Ocean Voyagers", "Aviation Pioneers", "Space Astronauts", "Early Aviators",
    "Modern Inventors", "Software Pioneers", "Tech Founders", "Social Entrepreneurs", "Civic Leaders",
    "Neighborhood Heroes", "Foster Parents", "Adoptive Families", "Family Patriarchs", "Family Matriarchs",
    "Sibling Bonds", "True Friends", "Loyal Allies", "Trusted Advisors", "Career Mentors",
    "Master Teachers", "Dedicated Coaches", "Youth Mentors", "Spiritual Guides", "Philosophical Thinkers",
    "Ancient Philosophers", "Enlightenment Thinkers", "Moral Philosophers", "Political Theorists", "Economic Thinkers",
    "Constitutional Framers", "Founding Figures", "Freedom Fighters", "Anti-War Activists", "Climate Activists",
    "Animal Advocates", "Community Organizers", "Humanitarian Doctors", "Field Nurses", "Emergency Responders",
    "Crisis Counselors", "Volunteer Firefighters", "Search Rescuers", "Disaster Volunteers", "Caregiver Heroes",
    "Hospice Volunteers", "Literacy Volunteers", "Community Elders", "Living Legends", "Quiet Achievers",
    "Reluctant Heroes", "Standing Up", "Speaking Truth", "Whistleblower Bravery", "Defying Odds",
    "Resilient Survivors", "Overcoming Adversity", "Triumphing Tragedy", "Inspiring Biographies", "Character Strengths",
    "Personal Integrity", "Moral Conviction", "Selfless Acts", "Everyday Kindness", "Radically Generous",
    "Helping Strangers", "Collective Courage", "Grassroots Heroes", "Everyday Citizens", "Modern Saints",
    "Public Intellectuals", "Empathetic Listeners", "Bridge Builders", "Peacemaker Spirits", "Social Visionaries",
    "Courageous Journalists", "War Correspondents", "Humanitarian Photographers", "Documentary Filmmakers", "Civil Servants",
    "Diplomatic Corps", "Respected Elders", "Guiding Lights", "Wisdom Keepers", "Cultural Custodians",
    "Master Musicians", "Virtuoso Performers", "Sculpture Masters", "Master Architects", "Master Builders",
    "Visionary Directors", "Master Playwrights", "Literary Giants", "Poet Laureates", "Epic Storytellers",
    "Oral Historians", "Folk Musicians", "Traditional Dancers", "Guild Masters", "Apprentice Mentors",
    "Village Elders", "Tribal Chiefs", "Spiritual Elders", "Interfaith Leaders", "Bridge Crossers"
]

CREATIVITY = [
    # 1-word
    "Imagination", "Aesthetics", "Improvisation", "Storytelling", "Symbolism",
    "Originality", "Expression", "Metaphor", "Sculpture", "Calligraphy",
    "Choreography", "Composition", "Cinematography", "Illustration", "Typography",
    "Ceramics", "Literature", "Poetry", "Drama", "Melody",
    "Harmony", "Rhythm", "Texture", "Satire", "Collage",
    "Animation", "Fiction", "Nonfiction", "Playwriting", "Novelty",
    "Iconography", "Surrealism", "Dadaism", "Expressionism", "Modernism",
    "Cubism", "Impressionism", "Minimalism", "Romanticism", "Renaissance",
    # 2-word
    "Creative Process", "Artistic Expression", "Visual Arts", "Performing Arts", "Creative Writing",
    "Graphic Design", "Industrial Design", "Interior Architecture", "Landscape Design", "Architectural Form",
    "Abstract Art", "Figurative Art", "Street Art", "Public Murals", "Digital Art",
    "Generative Art", "Concept Art", "Character Design", "Storyboard Art", "Stop Motion",
    "Voice Acting", "Screen Acting", "Stage Acting", "Musical Theater", "Modern Dance",
    "Classical Ballet", "Jazz Improvisation", "Classical Music", "Chamber Music", "Music Production",
    "Sound Design", "Audio Engineering", "Film Scoring", "Acoustic Resonance", "Vocal Harmony",
    "Songwriting Craft", "Lyric Writing", "Poetic Meter", "Free Verse", "Flash Fiction",
    "Short Stories", "Novel Writing", "World Building", "Character Arc", "Plot Development",
    "Narrative Structure", "Dialogue Writing", "Creative Nonfiction", "Memoir Writing", "Travel Writing",
    "Satirical Writing", "Stand-Up Comedy", "Sketch Comedy", "Dark Humor", "Visual Humor",
    "Dramatic Irony", "Stage Design", "Lighting Design", "Costume Design", "Fashion Design",
    "Haute Couture", "Sustainable Fashion", "Textile Arts", "Pattern Making", "Printmaking Techniques",
    "Woodcut Printing", "Screen Printing", "Darkroom Photography", "Film Photography", "Street Photography",
    "Portrait Photography", "Landscape Photography", "Color Theory", "Golden Ratio", "Negative Space",
    "Visual Balance", "Typography Design", "Font Pairing", "Brand Identity", "Logo Design",
    "Packaging Design", "Motion Graphics", "Visual Effects", "CGI Animation", "Virtual Production",
    "Indie Filmmaking", "Documentary Filmmaking", "Cinematographic Framing", "Color Grading", "Sound Mixing",
    "Foley Artistry", "Ambient Sound", "Environmental Storytelling", "Game Design", "Interactive Fiction",
    "World Lore", "Creative Blocks", "Overcoming Resistance", "Creative Flow", "Artistic Vision",
    "Finding Voice", "Serendipitous Ideas", "Cross-Pollination", "Divergent Ideas", "Brainstorming Sessions",
    "Rapid Ideation", "Prototype Sketching", "Ink Drawing", "Watercolor Painting", "Oil Painting",
    "Acrylic Techniques", "Mixed Media", "Ceramic Sculpting", "Stone Carving", "Metalworking Craft",
    "Woodworking Art", "Handcrafted Furniture", "Folk Art", "Traditional Crafts", "Cultural Expression",
    "Indigenous Art", "Sacred Art", "Mosaic Tiles", "Stained Glass", "Art Conservation",
    "Museum Curation", "Art Criticism", "Aesthetic Philosophy", "Visual Metaphor", "Symbolic Meaning",
    "Expressive Brushwork", "Tonal Harmony", "Dynamic Contrast", "Rhythmic Movement", "Linear Perspective",
    "Atmospheric Perspective", "Monochrome Palette", "Chiaroscuro Technique", "Palette Knives", "Pastel Drawings",
    "Etching Techniques", "Lithography Prints", "Book Binding", "Paper Craft", "Origami Sculptures",
    "Glass Blowing", "Enamel Jewelry", "Metal Casting", "Bronze Statues", "Wood Turning"
]
