# Category 5: Career (Target: 182)
# Category 6: Education (Target: 182)

CAREER = [
    # 1-word
    "Leadership", "Mentorship", "Entrepreneurship", "Networking", "Productivity",
    "Delegation", "Negotiation", "Specialization", "Freelancing", "Promotion",
    "Resignation", "Interviewing", "Sabbatical", "Management", "Overwork",
    "Craftsmanship", "Professionalism", "Multitasking", "Telecommuting", "Moonlighting",
    "Intrapreneurship", "Outsourcing", "Headhunting", "Downsizing", "Restructuring",
    "Solopreneurship", "Accountability", "Apprenticeship", "Specialist", "Generalist",
    "Workmanship", "Vocational", "Consultancy", "Colleagues", "Supervision",
    "Workplace", "Employability", "Workload", "Stipend", "Seniority",
    # 2-word
    "Remote Work", "Hybrid Work", "Job Hunting", "Career Growth", "Personal Branding",
    "Deep Work", "Time Management", "Public Speaking", "Executive Presence", "Salary Negotiation",
    "Performance Review", "Corporate Ladder", "Glass Ceiling", "Quiet Quitting", "Hustle Culture",
    "Work Ethic", "Team Dynamics", "Project Management", "Conflict Management", "Professional Development",
    "Skill Upgrading", "Resume Building", "Cover Letters", "Exit Interviews", "Job Switching",
    "Career Pivot", "Fractional Leadership", "Startup Culture", "Corporate Politics", "Office Ergonomics",
    "Asynchronous Work", "Standup Meetings", "Sprint Planning", "Agile Coaching", "Scrum Master",
    "Product Management", "Customer Success", "Sales Strategy", "Business Development", "Strategic Partnerships",
    "Venture Capital", "Angel Investing", "Bootstrapping Startups", "Seed Funding", "Series Funding",
    "Financial Modeling", "Market Research", "Competitive Analysis", "Brand Equity", "Customer Retention",
    "Churn Rate", "Profit Margins", "Revenue Streams", "Business Models", "Value Proposition",
    "Pitch Decks", "Investor Relations", "Board Meetings", "Corporate Governance", "Regulatory Compliance",
    "Risk Management", "Crisis Management", "Change Management", "Succession Planning", "Talent Acquisition",
    "Employee Retention", "Workplace Culture", "Company Values", "Diversity Hiring", "Inclusive Leadership",
    "Servant Leadership", "Transformational Leadership", "Micromanagement Pitfalls", "Autonomous Teams", "Cross-Functional Teams",
    "Team Building", "Offsite Retreats", "Company Morale", "Employee Engagement", "Pulse Surveys",
    "Performance Metrics", "Key Performance", "Objective Key", "North Star", "Accountability Framework",
    "Performance Improvement", "Constructive Feedback", "360 Feedback", "Peer Review", "Mentorship Programs",
    "Sponsorship Programs", "Reverse Mentorship", "Knowledge Sharing", "Internal Mobility", "Career Ladders",
    "Individual Contributor", "Management Track", "Technical Leadership", "Principal Engineers", "Engineering Culture",
    "Design Thinking", "User Research", "Client Management", "Stakeholder Management", "Vendor Relations",
    "Contract Negotiation", "Freelance Economy", "Gig Economy", "Side Hustles", "Passive Income",
    "Creator Economy", "Independent Consulting", "Small Business", "Family Business", "Franchise Models",
    "High-Pressure Jobs", "Shift Work", "Overtime Culture", "Toxic Workplaces", "Whistleblowing Ethics",
    "Golden Handcuffs", "Severance Packages", "Layoff Protocols", "Career Longevity", "Professional Network",
    "Alumni Networks", "Industry Conferences", "Trade Shows", "Thought Leadership", "Publishing Articles",
    "Technical Writing", "Executive Coaching", "Career Counseling", "Mid-Career Pivot", "Late-Career Transitions",
    "Retirement Transition", "Encore Careers", "Portfolio Careers", "Slash Careers", "Work Identity",
    "Job Satisfaction", "Meaningful Work", "Vocational Calling", "Passion Projects", "Pro Bono",
    "Corporate Volunteering", "Job Rotation", "Shadowing Programs", "Apprentice Programs", "Talent Pipelines",
    "Success Metrics", "Leadership Styles", "Decision Making", "Problem Framing", "Resource Allocation",
    "Budget Management", "Cost Optimization", "Capital Expenditure", "Operational Efficiency", "Workflow Automation",
    "Process Optimization", "Quality Assurance", "Continuous Feedback", "Performance Benchmarking", "Competitive Advantage"
]

EDUCATION = [
    # 1-word
    "Pedagogy", "Literacy", "Curriculum", "Homeschooling", "Academics",
    "Tutoring", "Scholarship", "Polymathy", "Epistemology", "Didactics",
    "Andragogy", "Schooling", "Examination", "Homework", "Graduation",
    "Classrooms", "Universities", "Erudition", "Cognition", "Matriculation",
    "Coeducation", "Intellect", "Campus", "Semester", "Syllabus",
    "Mentoring", "Faculty", "Students", "Lectures", "Academia",
    "Scholar", "Textbooks", "Educators", "Classmates", "Vocational Guilds",
    "Illiteracy", "Dyslexia", "Pedagogue", "Polymath", "Scholarships",
    # 2-word
    "Higher Education", "Early Childhood", "STEM Education", "Liberal Arts", "Continuous Learning",
    "Online Courses", "Vocational Training", "Student Debt", "Standardized Testing", "Active Learning",
    "Flipped Classroom", "Experiential Learning", "Project-Based Learning", "Montessori Method", "Waldorf Education",
    "Public Schools", "Private Schools", "Charter Schools", "Community Colleges", "Trade Schools",
    "Coding Bootcamps", "Micro-Credentials", "Digital Literacy", "Financial Literacy", "Peer Learning",
    "Study Habits", "Note Taking", "Speed Reading", "Memory Techniques", "Spaced Repetition",
    "Flashcard Systems", "Active Recall", "Socratic Method", "Inquiry-Based Learning", "Collaborative Learning",
    "Student Engagement", "Attention Span", "Classroom Management", "Teacher Training", "Teacher Burnout",
    "School Funding", "Education Reform", "Curriculum Design", "Core Curriculum", "Interdisciplinary Studies",
    "Classical Education", "Bilingual Education", "Language Immersion", "Dual Enrollment", "Advanced Placement",
    "International Baccalaureate", "Grade Inflation", "Pass-Fail Systems", "Open-Book Exams", "Oral Examinations",
    "Standardized Curricula", "School Vouchers", "Equal Access", "Rural Schools", "Urban Education",
    "Special Education", "Neurodivergent Learning", "Inclusive Classrooms", "Gifted Programs", "Remedial Education",
    "Adult Literacy", "Continuing Education", "Corporate Training", "Executive Education", "Lifelong Learning",
    "Knowledge Retention", "Cognitive Load", "Dual-Coding Theory", "Metacognition Skills", "Study Groups",
    "Academic Integrity", "Plagiarism Ethics", "Honor Codes", "Academic Research", "Peer-Reviewed Journals",
    "Open-Access Publishing", "University Endowments", "Campus Culture", "Student Life", "Dormitory Living",
    "Extracurricular Activities", "Debate Clubs", "Student Government", "Academic Decathlon", "Science Fairs",
    "Math Competitions", "Summer Internships", "Study Abroad", "Cultural Exchange", "Foreign Languages",
    "Classical Languages", "Philosophy Education", "History Education", "Science Literacy", "Environmental Education",
    "Outdoor Classrooms", "Forest Schools", "Play-Based Learning", "Kindergarten Readiness", "Phonics Instruction",
    "Whole Language", "Reading Comprehension", "Essay Writing", "Academic Writing", "Critical Analysis",
    "Socratic Seminars", "Lecture Halls", "Virtual Classrooms", "MOOC Platforms", "Remote Tutoring",
    "Adaptive Learning", "Gamified Learning", "EdTech Tools", "Interactive Whiteboards", "Educational Podcasting",
    "Open Educational", "Free Textbooks", "Digital Libraries", "Research Libraries", "Primary Sources",
    "Critical Inquiry", "Independent Study", "Thesis Defense", "Graduate School", "Doctoral Studies",
    "Postdoctoral Research", "Academic Tenure", "Ivory Tower", "Student Well-Being", "School Counselors",
    "Parent-Teacher Conferences", "Educational Psychology", "Child Development", "Cognitive Development", "Behavioral Interventions",
    "Student Retention", "Graduation Rates", "Dropout Prevention", "Alternative Schools", "Night Classes",
    "Summer School", "Remedial Reading", "Math Anxiety", "Science Labs", "Field Trips",
    "Hands-On Learning", "Kinesthetic Learning", "Visual Learning", "Auditory Learning", "Multimodal Learning"
]
