# Category 1: Technology (Target: 182)
# Category 2: Society (Target: 182)

TECHNOLOGY = [
    # 1-word
    "Cybersecurity", "Automation", "Microchips", "Cryptography", "Blockchain",
    "Robotics", "Supercomputing", "Biometrics", "Nanotechnology", "Metaverse",
    "Telecommunications", "Semiconductors", "Telehealth", "Virtualization", "Firmware",
    "Wearables", "Drones", "Satellites", "Exoskeletons", "Encryption",
    "Sensors", "Avionics", "Cyberwarfare", "Microcontrollers", "Mainframes",
    "Infosec", "Deepfakes", "Streaming", "Telemetry", "Hackathons",
    "Broadband", "Supercomputers", "Nanobots", "Microprocessors", "Biocomputing",
    "Algorithmic", "Optoelectronics", "Mechatronics", "Biochips", "Cybernetics",
    # 2-word
    "Artificial Intelligence", "Machine Learning", "Deep Learning", "Cloud Computing", "Edge Computing",
    "Quantum Computing", "Neural Networks", "Computer Vision", "Natural Language", "Big Data",
    "Smart Contracts", "Digital Privacy", "Facial Recognition", "Autonomous Vehicles", "Generative AI",
    "Digital Twins", "Smart Cities", "Virtual Reality", "Augmented Reality", "Mixed Reality",
    "Voice Assistants", "Prompt Engineering", "Zero Trust", "Data Mining", "Mobile Apps",
    "Social Media", "Recommender Systems", "Spatial Computing", "Cyber Ethics", "Brain-Computer Interface",
    "Silicon Valley", "Predictive Analytics", "Synthetic Media", "Tech Monopolies", "Tech Startups",
    "Digital Identity", "Web Development", "Software Architecture", "User Experience", "User Interface",
    "Cloud Native", "Edge Devices", "Serverless Computing", "Continuous Delivery", "Agile Development",
    "Distributed Systems", "High Availability", "Fault Tolerance", "Screen Time", "Digital Detox",
    "Open Source", "Version Control", "Hardware Acceleration", "Graphic Processors", "Mobile Payments",
    "Digital Currencies", "Central Banking", "Robotic Surgery", "Smart Homes", "Smart Grids",
    "Ambient Computing", "Wearable Devices", "Biohacking Tech", "Synthetic Biology", "Quantum Sensors",
    "Satellite Internet", "5G Networks", "6G Wireless", "Fiber Optics", "Cloud Storage",
    "Data Centers", "Autonomous Drones", "Drone Delivery", "Robot Ethics", "Software Licensing",
    "Intellectual Property", "Digital Rights", "Content Moderation", "Search Engines", "Recommendation Algorithms",
    "Microservice Architecture", "Code Generation", "Bug Bounties", "Penetration Testing", "Zero-Day Exploits",
    "Social Engineering", "Phishing Attacks", "Ransomware Threats", "Cloud Security", "Threat Intelligence",
    "Biometric Authentication", "Two-Factor Authentication", "Single Sign-On", "Identity Theft", "Dark Web",
    "Surveillance Capitalism", "Data Sovereignty", "Algorithmic Bias", "Autonomous Weapons", "Humanoid Robots",
    "Industrial Automation", "Cobot Systems", "Warehouse Robotics", "Self-Driving Trucks", "Flying Cars",
    "Battery Technology", "Wireless Charging", "Smart Glass", "Haptic Feedback", "Neural Implants",
    "Silicon Photonics", "Semiconductor Fabrication", "Cleanroom Tech", "Chip Shortage", "Tech Infrastructure",
    "Legacy Systems", "Technical Debt", "Code Review", "Pair Programming", "DevOps Culture",
    "Quantum Supremacy", "Quantum Encryption", "Decentralized Finance", "Web3 Protocols", "Tokenized Assets",
    "Digital Assets", "Smart Wallets", "Mesh Networks", "Edge AI", "Computer Hardware",
    "Operating Systems", "Linux Kernel", "Open Standards", "Open Hardware", "3D Printing",
    "Additive Manufacturing", "Rapid Prototyping", "Automated Testing", "Continuous Integration", "Database Design",
    "Relational Databases", "Data Warehousing", "Data Lakes", "Graph Databases", "Information Retrieval",
    "Semantic Web", "Internet Protocols", "Network Security", "Packet Sniffing", "Firewall Architecture",
    "Endpoint Protection", "Malware Analysis", "Memory Safety", "Compiler Optimization", "Parallel Computing",
    "Instruction Sets", "Embedded Systems", "System Architecture", "Software Reliability", "API Design",
    "Microcode Updates", "Digital Watermarking", "Speech Synthesis", "Gesture Recognition", "Optical Storage",
    "Solid-State Drives", "Magnetic Storage", "Liquid Cooling", "Quantum Key", "Digital Signatures",
    "Public Key", "Smart Appliances", "Connected Vehicles", "Telematics Systems", "Location Services"
]

SOCIETY = [
    # 1-word
    "Urbanization", "Democracy", "Globalization", "Consumerism", "Immigration",
    "Gentrification", "Polarization", "Nationalism", "Secularism", "Capitalism",
    "Socialism", "Philanthropy", "Bureaucracy", "Multiculturalism", "Individualism",
    "Collectivism", "Citizenship", "Inequality", "Poverty", "Propaganda",
    "Censorship", "Egalitarianism", "Pluralism", "Demographics", "Suburbs",
    "Cosmopolitanism", "Populism", "Civics", "Activism", "Materialism",
    "Modernity", "Patriotism", "Authoritarianism", "Tribalism", "Electorate",
    "Sovereignty", "Constitution", "Voluntarism", "Solidarity", "Egalitarian",
    # 2-word
    "Civil Rights", "Public Policy", "Social Mobility", "Income Inequality", "Cultural Diversity",
    "Free Speech", "Cancel Culture", "Social Justice", "Community Building", "Civic Engagement",
    "Public Goods", "Universal Healthcare", "Affordable Housing", "Voting Rights", "Criminal Justice",
    "Prison Reform", "Police Accountability", "Digital Commons", "Information Warfare", "Media Literacy",
    "Fake News", "Public Transport", "Urban Planning", "Public Health", "Welfare State",
    "Social Safety", "Wealth Distribution", "Labor Unions", "Minimum Wage", "Living Wage",
    "Generational Divide", "Baby Boomers", "Generation Z", "Cultural Heritage", "Historical Memory",
    "Indigenous Rights", "Gender Equality", "Human Rights", "Due Process", "Constitutional Checks",
    "Direct Democracy", "Representative Democracy", "Voter Turnout", "Grassroots Movements", "Political Polarization",
    "Echo Chambers", "Filter Bubbles", "Public Opinion", "Civil Disobedience", "Peaceful Protest",
    "Social Stigma", "Taboo Topics", "Public Housing", "Food Deserts", "Homelessness Solutions",
    "Mental Healthcare", "Drug Decriminalization", "Substance Abuse", "Rehabilitation Programs", "Community Policing",
    "Restorative Justice", "Capital Punishment", "Juvenile Justice", "Immigration Reform", "Refugee Crisis",
    "Border Security", "Asylum Seekers", "Migrant Workers", "Brain Drain", "Diaspora Communities",
    "Cultural Assimilation", "Social Cohesion", "Public Trust", "Institutional Decay", "Political Corruption",
    "Campaign Finance", "Lobbying Influence", "Government Transparency", "Open Government", "Freedom Information",
    "Surveillance State", "Privacy Rights", "Whistleblower Protection", "Press Freedom", "Investigative Journalism",
    "Local News", "Public Broadcasting", "Social Stratification", "Class Warfare", "Middle Class",
    "Working Class", "Rural Decline", "Urban Sprawl", "Smart Mobility", "Bike Infrastructure",
    "Pedestrian Zones", "Public Parks", "Green Spaces", "Third Places", "Social Isolation",
    "Civic Pride", "Town Halls", "Local Governance", "Decentralized Governance", "Participatory Budgeting",
    "Universal Basic", "Basic Income", "Digital Divide", "Broadband Access", "Public Libraries",
    "Community Centers", "Food Insecurity", "Soup Kitchens", "Volunteer Work", "Charity Organizations",
    "Nonprofit Sector", "Social Entrepreneurship", "Corporate Responsibility", "Fair Trade", "Ethical Consumerism",
    "Boycott Movements", "Consumer Rights", "Tenant Rights", "Property Rights", "Eminent Domain",
    "Zoning Laws", "Historic Preservation", "Cultural Diplomacy", "International Relations", "Global Governance",
    "Treaty Agreements", "Humanitarian Aid", "Disaster Relief", "Global Poverty", "Living Standards",
    "Quality Life", "Social Welfare", "Public Sanitation", "Clean Water", "Energy Poverty",
    "Family Policy", "Parental Leave", "Childcare Access", "Elderly Care", "Aging Population",
    "Retirement Security", "Pension Systems", "Intergenerational Wealth", "Inheritance Taxes", "Progressive Taxation"
]
